/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppDetectionsRouteImport } from './routes/_app/detections'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app/assets.$assetId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectionsRoute = AppDetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/detections': typeof AppDetectionsRoute
  '/upload': typeof AppUploadRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/detections': typeof AppDetectionsRoute
  '/upload': typeof AppUploadRoute
  '/': typeof AppIndexRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/detections': typeof AppDetectionsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detections' | '/upload' | '/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/detections' | '/upload' | '/' | '/assets/$assetId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/detections'
    | '/_app/upload'
    | '/_app/'
    | '/_app/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detections': {
      id: '/_app/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof AppDetectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDetectionsRoute: typeof AppDetectionsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDetectionsRoute: AppDetectionsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
